version = 0.1
[default.deploy.parameters]
stack_name = "cloud-resume-api"
resolve_s3 = true
s3_prefix = "cloud-resume-api"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
