name: Deploy Frontend to S3

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      S3_BUCKET: resumestack-resumewebsitebucketed717468-z6qfbqse2nnd

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync frontend to S3
        run: aws s3 sync ./frontend s3://$S3_BUCKET --delete

      - name: Post-deploy confirmation
        run: echo "Frontend deployed to S3 successfully."