name: Deploy CDK Infrastructure

on:
  push:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/deploy-cdk.yml'

jobs:
  deploy-cdk:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install CDK dependencies
        working-directory: infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  

      - name: Deploy CDK Stack
        working-directory: infrastructure
        run: cdk deploy --require-approval never

      - name: Post-deploy check
        run: echo "CDK infrastructure deployed."
